name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTOR: pop-cli

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Check Feature Contracts Excl.
        run: cargo check --no-default-features --features contract

      - name: Check Features Parachain Excl.
        run: cargo check --no-default-features --features parachain

      - name: Build default features
        run: cargo build

  parachain-integration-tests:
    needs: lint
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true
          target: wasm32-unknown-unknown
          components: rust-src, clippy

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Install packages (Linux)
        if: matrix.os == 'ubuntu-latest'
        uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Install packages (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install protobuf
          protoc --version

      - name: Run integration tests
        run: cargo test --package pop-cli --test parachain -- parachain_lifecycle --exact --show-output
