name: ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  GITHUB_ACTOR: pop-cli

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check formatting
        run: cargo fmt --all -- --check

  build:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Check Feature Contracts Excl.
        run: cargo check --no-default-features --features contract

      - name: Check Features Parachain Excl.
        run: cargo check --no-default-features --features parachain

      - name: Build default features
        run: cargo build

  deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: EmbarkStudios/cargo-deny-action@v1

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/build-push-action@v5

  unit-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Run unit tests
        run: cargo test --lib --bins

  coverage:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --lib --bins --codecov --output-path codecov.json

      - name: Upload to codecov.io
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true
  
  build-integration-tests:
    strategy:
      fail-fast: false
      matrix:
        # We want newer versions than 'latest' here to have current wasm-opt
        os: ["ubuntu-22.04", "macos-12"]
    runs-on: ${{ matrix.os }}
    env:
      RUST_BACKTRACE: full
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Install nextest
        uses: taiki-e/install-action@v2.34.3
        with:
          tool: nextest

      - name: Build and archive tests
        run: cargo nextest archive --cargo-profile debug-ci --workspace --all-features --archive-file nextest-archive-${{ matrix.os }}.tar.zst
      - name: Upload archive to workflow
        uses: actions/upload-artifact@v4
        with:
          name: nextest-archive-${{ matrix.os }}
          path: nextest-archive-${{ matrix.os }}.tar.zst

  contract-integration-tests:
    needs: build-tests
    strategy:
      fail-fast: false
      matrix:
        # We want newer versions than 'latest' here to have current wasm-opt
        os: ["ubuntu-22.04", "macos-12"]
        partition: [1, 2]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Install nextest
        uses: taiki-e/install-action@v2.34.3
        with:
          tool: nextest

      - name: Download archive
        uses: actions/download-artifact@v4
        with:
          name: nextest-archive-${{ matrix.os }}

      - name: Run integration tests
        run: cargo nextest --no-default-features --features contract --test contract

  parachain-integration-tests:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: "./.github/actions/init"
        with:
          git-user: ${{ env.GITHUB_ACTOR }}

      - name: Run integration tests
        run: cargo test --no-default-features --features parachain --test parachain
